# config.yml
# Test configuration
# A Wickert, 23 Oct 2022

# Should timeseries have no subcategories?
timeseries:
        datafile: '...'

initial_conditions:
        water_reservoir_effective_depths__m:
                - 0
                - 0
        snowpack__m: 0

catchment:
        drainage_basin_area__km2: 1000
        water_year_start_month: 10

reservoirs:
        e_folding_residence_times__days:
                - 15
                - 60
        exfiltration_fractions:
                - 0.8
                - 1.0
        maximum_effective_depths__m:
                - .inf
                - .inf

snowmelt:
        # mm SWE per positive degC day
        PDD_melt_factor: 0.5
